name: GitHub Actions Maven Build
on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: create-json
        uses: jsdaniell/create-json@v1.2.2

      - name: create-api-key
          id: create-api-key
          uses: jsdaniell/create-json@v1.2.2
          with:
            name: "api_key.json"
            json: ${{ secrets.API_KEY }}
#            dir: 'src/'

      - name: create-google-credentials
        id: create-google-credentials
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "my-project-1521814632192-74db441a7e07.json"
          json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
#          dir: 'src/'

      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2
       
      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Step 3 - Have GitHub Actions Build Maven Project
        run: mvn -B package --file pom.xml
      - name: Step 4 - List the current directory
        run: ls -a
      - name: Step 5 - Run project tests with maven
        run: mvn clean test
          
          
      
